# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('name', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together=set([('currency', 'user')]),
        ),
    ]
