# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 11:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20171214_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyperdayrate',
            options={'ordering': ['-created'], 'verbose_name': 'Currency Per Day Rate', 'verbose_name_plural': 'Currency Per Day Rates'},
        ),
        migrations.AlterModelOptions(
            name='currencyperhourrate',
            options={'ordering': ['-created'], 'verbose_name': 'Currency Per Hour Rate', 'verbose_name_plural': 'Currency Per Hour Rates'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16),
        ),
    ]
